apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    aws-ebs-tagger/tags: '{"Application": "influxdb-historian", "Namespace": "<namespace>","Backup_Plan":
      "default"}'
  labels:
    app.kubernetes.io/instance: historian
    app.kubernetes.io/name: influxdb
  name: influxdb-historian-storage-new-influxdb-historian-0
  namespace: <namespace>
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: <size>Gi
  storageClassName: eks-gp3-encrypted
  volumeMode: Filesystem
  volumeName: <pv-new>